/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gim' at '3/5/14 10:12 PM' with Gradle 1.11
 *
 * @author gim, @date 3/5/14 10:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
